name: RegexFilter
main: com.github.Heliwr.RegexFilter.RegexFilter
author: FloydATC, Heliwr
version: 1.2
description: >
             Filter chat messages using regular expressions
commands:
  regex:
    description: RegexFilter control
    usage: /<command> reload
